name: app-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java20
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 20

      - name: Gradle Build
        shell: bash
        run: |
          app/gradlew build
          echo "$(find /home/.gradle/wrapper/dists/ -name gradle | xargs ls -tr | tail -n 1 | xargs dirname)" >> $GITHUB_PATH

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          build-root-directory: app
          gradle-version: 8.2
          arguments: build

      - name: Publish test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          workingDirectory: app
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
